 all:
   children:
     webservers:
       hosts: 
         web1.aws:
           private_ip: 13.201.54.147
         web2.aws:
           private_ip: 13.233.198.214
     db:
       hosts:
         db.aws:
           private_ip: 65.0.86.36
     storage:
       hosts:
         file.aws:
           private_ip: 13.233.197.220
     lb:
       hosts:
         lb.aws:
           private_ip: 13.233.108.98
